server {
    listen 8082;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php_3102:9000;   # "php" este es el nombre del servicio desde el docker compose
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}